### PR TITLE
LPS-93568 Prevent unintended configuration deletions across cluster

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LPS-93568 Prevent unintended configuration deletions across cluster

### CODE REVIEW

**Comment by jrao** [comment]
ci:test

**Comment by jrao** [comment]
ci:test:sf

**Comment by jrao** [comment]
ci:test:clustering

**Comment by jrao** [comment]
The Poshi reports for the ci:test:clustering failures all seem to fail a this point:

`AssertElementPresent(locator1 = "UserBar#USER_AVATAR_IMAGE");`

This doesn't seem related to my changes which how configurations are updated across clusters.

I also created a dummy PR here for comparison: https://github.com/jrao/liferay-portal/pull/46

I'm not sure why only 1 test runs there instead of the 12 here. Also not sure why there's a compile failure there but not here. Both that branch and this one have the same parent commit from master: 5c27f0521d86f24bfa53a540d4f4665961c4187e

**Comment by ChrisKian** [comment]
Looks good, sent to https://github.com/drewbrokke/liferay-portal/pull/792

**Pull request closed without merging**
