### PR TITLE
LPS-74022 Solr Unable to Sort on Custom Structure Date fields

### PR DESCRIPTION
**Pull request by arboliveira**
Hi Chris! Thanks for your work on this. I went ahead and typified the field names of String sortable fields. Changing the value of the public constant `Field.SORTABLE_FIELD_SUFFIX` would be a breaking change, and would have been rejected down the road. I noticed the `DLFileEntrySearchTest` and `JournalArticleSearchTest` integration tests could replicate this bug running against Solr; both are passing now.

Please verify the original steps to reproduce under Portal itself, and see if you notice any side effects or strange behavior. If everything seems okay I'll submit this fix.

Thanks again!

### CODE REVIEW

**Comment by arboliveira** [comment]
Test failures seem unrelated.

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
ci:retest

**Comment by ChrisKian** [comment]
Looks good to me!

**Comment by arboliveira** [comment]
Submitted as https://github.com/brianchandotcom/liferay-portal/pull/51015. Thanks!!

**Pull request closed without merging**
