### PR TITLE
LPS-76228 - Web content that links to other content in DXP fails to load upon import.

### PR DESCRIPTION
**Pull request by wanderlast**
Hi Chris!
LPS: https://issues.liferay.com/browse/LPS-76228

**The Issue:**
Currently, if a web content that contains a URL link to another page in the portal is displayed in a WCM Display and then exported, the WCM Display will appear blank upon import. This is due to the fact that the linked portal page is considered a missing reference and overwrites the correct layout for the page which the link is located on. To fix the issue, we check if the layout's group and layoutset match the layout being overwritten before attempting to overwrite it.

**This issue is not reproducible in master**. It was fixed in master through a Technical Task (LPS-67838). However, this is being submitted to master due to a request made by Tamás [here](https://github.com/matethurzo/liferay-portal-ee/pull/222#issuecomment-360521820), which mentions that since the code exists in master it may still affect the portal in ways we're simply not aware of.

Please let me know if you have any questions I can answer. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test

**Comment by ChrisKian** [comment]
Hey @wanderlast,
Can you run the test suite locally with your changes?  This way we will know for sure if the failures are due to your changes.

**Comment by wanderlast** [comment]
Hi @ChrisKian, I've run the Journal integration tests and they passed. Would you like me to re-run CI again?

**Comment by ChrisKian** [comment]
I'll retest them now, just in case they pass.

**Comment by ChrisKian** [comment]
ci:test

**Comment by wanderlast** [comment]
ci:close

**Comment by wanderlast** [comment]
Resent at #26 with fix for failed tests.

**Pull request closed without merging**
