### PR TITLE
LPS-92252 Make portletRequestModelFactory available to template context

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LPS-92252 Make portletRequestModelFactory available to template context

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jrao** [comment]
ci:test:sf

**Comment by jrao** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Forwarded to https://github.com/ealonso/liferay-portal/pull/2261

**Pull request closed without merging**
