### PR TITLE
[TS] LPS-106589 User session is not terminated after entering invalid login credentials in Account Settings multiple times (max lockout)

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-106589

The solution is based on the one on https://issues.liferay.com/browse/LPS-53189

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
Hey @NorbertKocsis,
Besides the small SF error, the pull looks pretty good.  I was wondering if it would be useful to display an error message after the user is logged out.  Currently, the user is redirected to the home page, but no message is output, which might confuse the user as to how/why the redirect occurred.

If this is something which can be done, let me know.  Otherwise, if it's not possible, I will forward your pull with the SF fix as well.
Thanks!

**Comment by NorbertKocsis** [comment]
Hi,

I'm looking into it. The UserAdmin portlet's error page can't be used as the user wont have permission to view it after he is logged out.

Br,
Norbert

**Comment by NorbertKocsis** [comment]
Hi,

I don't really see a nice way to show the error, and after entering a wrong pasword several times I think the user will figure what happened. Otherwise if he tries to log back in the portal will tell he is locked out.

So, I guess it's okay this way

Br,
Norbert

**Comment by ChrisKian** [comment]
Thanks for looking into that Norbert.  I've forwarded the PR here: https://github.com/drewbrokke/liferay-portal/pull/957

**Pull request closed without merging**
