### PR TITLE
[TS] LPS-149670 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
#### Description

Valencian language is recognized under ISO 659-1 standard.
It has assigned the `ca-ES-VALENCIA` locale code from **Java 8.**

See https://www.localeplanet.com/java/ca-ES-VALENCIA/index.html

#### Solution proposed

Including the `ca-ES-VALENCIA` locale as _locales_ and _locales.beta_ properties item.

#### References:
https://issues.liferay.com/browse/LPS-149670

Best.

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
ci:test:relevant

**Review by erickmonteiroo — APPROVED** [review]
LGTM

**Comment by erickmonteiroo** [comment]
Thank you for you patience on this! 

see https://github.com/liferay-usm/liferay-portal/pull/504

**Comment by joelgarman** [comment]
Since it has been forwarded can this pull be closed?

**Comment by jorgediaz-lr** [comment]
ci:close

**Pull request closed without merging**
