### PR TITLE
LPS-90376 Set window state even for action URLs so product menu is rendered

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LPS-90376 Set window state even for action URLs so product menu is rendered
Passing SF test: https://github.com/jrao/liferay-portal/pull/42#issuecomment-466050999
Revelant test (not sure how to interpret results): https://github.com/jrao/liferay-portal/pull/42#issuecomment-466092536

### CODE REVIEW

**Comment by jrao** [comment]
@ChrisKian Can you make any recommendations regarding how to check if this update will have side effects?

**Comment by ChrisKian** [comment]
Hey @jrao,

The easiest way to do so is to run the ci tests.  Since your changes could impact lots of areas, I recommend running all tests, not just the relevant.  I'll do so now.

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:stop

**Comment by ChrisKian** [comment]
ci:test

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
Forwarded to https://github.com/lipusz/liferay-portal/pull/250.  I'm not 100% sure this will be the correct solution, but I've dug around for most of the day any haven't found any problems it may cause, or a better way to solve the issue.

**Pull request closed without merging**
