### PR TITLE
LPS-92069 Use assetEntry instead of assetRenderer to get class PK to avoid no such asset exception

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LPS-92069 Use assetEntry instead of assetRenderer to get class PK to avoid no such asset exception

### CODE REVIEW

**Comment by jrao** [comment]
ci:test:sf

**Comment by jrao** [comment]
ci:test:relevant

**Comment by jrao** [comment]
@ChrisKian fixes https://github.com/liferay/liferay-portal-ee/pull/12991

**Comment by ChrisKian** [comment]
Hey @jrao, can you check the failing test and make sure it's not due to your changes?  It looks like it might be related.

**Comment by ChrisKian** [comment]
See https://github.com/jrao/liferay-portal/pull/44

**Pull request closed without merging**
