### PR TITLE
LPS-204063, LPS-204064, LPS-204065

### PR DESCRIPTION
**Pull request by cdbm**
[Task Link](https://liferay.atlassian.net/browse/LPD-5132)

### CODE REVIEW

**Comment by cdbm** [comment]
ci:test:sf

**Comment by cdbm** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Thanks @cdbm, I did see two of the references were likely still in use, but I reverted those changes and sent the third reference off for removal, see https://github.com/liferay-appsec/liferay-portal/pull/1595

See [this comment](https://github.com/liferay-appsec/liferay-portal/pull/1595) and [this one too](https://liferay.atlassian.net/browse/LPD-5502?focusedCommentId=2564546).

**Pull request closed without merging**
