### PR TITLE
LPS-111718 - Prevent calendar booking's asset fields from being overwritten

### PR DESCRIPTION
**Pull request by wanderlast**
From @kevhlee:

> Ticket: https://issues.liferay.com/browse/LPS-111718
> 
> When the user updates a calendar booking, a new booking is created with the update and the old one is deleted, as seen [here](https://github.com/kevhlee/liferay-portal/blob/LPS-111718/modules/apps/calendar/calendar-service/src/main/java/com/liferay/calendar/service/impl/CalendarBookingLocalServiceImpl.java#L1386-L1458). The issue is that, when updates are made using the "Save" button or when the RSVP value is changed, the assets of the old booking are not stored in the service context and therefore not passed to the new booking. The service context is used to update the asset fields of calendar bookings, as seen [here](https://github.com/kevhlee/liferay-portal/blob/LPS-111718/modules/apps/calendar/calendar-service/src/main/java/com/liferay/calendar/service/impl/CalendarBookingLocalServiceImpl.java#L267-L271). To fix this issue, I made sure that the assets of the old booking are stored in the service context before the booking is updated.
> 
> With regards,
> Kevin

Previous pull was: https://github.com/inacionery/liferay-portal/pull/588

### CODE REVIEW

**Comment by wanderlast** [comment]
SF passed here: https://github.com/wanderlast/liferay-portal/pull/63#issuecomment-617903978

**Comment by ChrisKian** [comment]
Hey @kevhlee and @wanderlast,
Just to confirm, did either of you test the failed tests mentioned here: https://github.com/inacionery/liferay-portal/pull/588#issuecomment-617195764?  I just want to make sure we don't fail the next PR to engineering for the same reason.  Thanks!

**Comment by wanderlast** [comment]
Hi @ChrisKian,
I can confirm that I ran the tests locally and none of the tests mentioned failed for me. Kevin also mentioned to me that he had tested himself and the only test that failed was the one that was identified as flaky and that it failed both with and without the changes.

**Comment by ChrisKian** [comment]
Perfect, thanks @wanderlast.  Sent to https://github.com/inacionery/liferay-portal/pull/597

**Comment by kevhlee** [comment]
Hi @ChrisKian,

Just confirming what Lianne said. I ran all of the functional tests on my machine and passed almost all of them. The ones I passed were all caused by the same `NullPointerException`. The test I failed was `CalendarCreateCalendar#ResizeAddedEventsViaEventBlock`. I can't pass this test on my environment, even on `master` with no changes.

**Pull request closed without merging**
