### PR TITLE
LPS-105757 isGroupAdmin() checks for a non-existent groupId attribute in the SearchContext

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-105757](https://issues.liferay.com/browse/LPS-105757).<br><br>Hey @ChrisKian, can you please double-check my change? I don't think search cares about the 'usersGroups' key, just the value, so we can keep the original field name.<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
@ChrisKian if the change looks good, feel free to squash the commits.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Changes look fine to me.  Sent back to you: https://github.com/drewbrokke/liferay-portal/pull/947

**Pull request closed without merging**
