### PR TITLE
LPS-112246 Permission setting with new top level PanelCategory

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @ChrisKian,

Could you please review this pull request?

I took over the issue from Norbert as he left the company.

I [added the changes](https://github.com/ChrisKian/liferay-portal/commit/c88e4d07ede3d2b9d26533621739e50f1e020561) you requested in https://github.com/ChrisKian/liferay-portal/pull/213#issuecomment-621473308

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hi @IstvanD,

I have two questions regarding the changes:
1. Is the "other" language key needed?  The language.properties file in portal-impl already has "other", so I believe it will already be pulled in from that file.
2. Do you have sample portlets to test with on master?  This will also be needed by QA to test the solution. 

I'll keep this PR open in the meantime, thanks!

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
Hi @ChrisKian 

you're right, there is no need for adding the "other" language key as the language.properties file in portal-impl already has "other".

Also, I uploaded a test module to the LPS and edited the reproduction steps accordingly to the QA can test the solution on master.

**Comment by ChrisKian** [comment]
Thanks for making those changes @IstvanD.  I've forwarded your PR here: https://github.com/drewbrokke/liferay-portal/pull/1233

**Pull request closed without merging**
