### PR TITLE
LPS-89521 - inherited sites should also be retrieved when checking for a user's groups

### PR DESCRIPTION
**Pull request by wanderlast**
Hi Chris!

https://issues.liferay.com/browse/LPP-32777
https://issues.liferay.com/browse/LPS-89521

This issue is relatively straightforward. Currently, if a user inherits a site through an organization that it is a member of (say OrgA is a member of TestSite and User1 is a member of OrgA)--User1 should therefore be a member of TestSite and be able to be assigned a site role for TestSite. This works correctly if you navigate to TestSite > Memberships > Users (User1 is listed properly) and then assign them a role through this menu. However, if you go through the Users and Organizations menu and Edit User > Roles, the option to add them does not appear. This is due to the use of selUser.getGroups() which specifically ignores any inherited groups. The change is to use an API that can account for and allow inherited groups to also be included. Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Looks good, send to https://github.com/pei-jung/liferay-portal/pull/337

**Pull request closed without merging**
