### PR TITLE
LPS-116317 Editing an Organization causes the Back Arrow and Cancel buttons to no longer function

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-116317](https://issues.liferay.com/browse/LPS-116317).<br><br>Hey @ChrisKian @kevhlee, thank you for sending me the fix at https://github.com/drewbrokke/liferay-portal/pull/1124. It worked well, but it gave me a chance to look over the component, and I saw many opportunities to clean things up (not directly related to the issue). Can you please look over my changes in the first two commits and verify that everything works as intended\? I marked the rest of the commits as "(unrelated)", since they are not required to fix this issue. Feel free to look them over if you'd like, but the main changes in this case are in the first two commits. Please let me know if you have any questions/comments. Thanks!<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Hi @drewbrokke,

I've tested the changes. The changes resolve the issue. Looks good!

**Comment by drewbrokke** [comment]
@ChrisKian if this looks good to you, go ahead and forward to Brian.

**Comment by ChrisKian** [comment]
ci:forward

**Pull request closed without merging**
