### PR TITLE
[TS] LPS-77366 Create a Config Admin entry to enable stricter permission checking on roles when editing the Permissions for a resource like a document or web article

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Dear Chris,

According to our normal code review process, I am sending this PR to you - please review my code changes and let me know if there is anything I should change.
If you find the changes ok please forward the pull to the next approver.

Link to the LPS ticket:
[LPS-77366](https://issues.liferay.com/browse/LPS-77366)

Manual testing shows that the fix correctly resolves the issue.

Thank you,
Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:test

**Comment by ChrisKian** [comment]
hey @peterpetrekanics,
I think you may have build the languages in the wrong module.  Could you fix this and resend your changes?

Feel free to force push back onto this PR, or you can close and resend if you'd prefer.  Thanks!

**Comment by peterpetrekanics** [comment]
ci:test

**Comment by peterpetrekanics** [comment]
Dear @ChrisKian,

Good catch, indeed the wrong language files were built.
Now I corrected this and pushed the changes back here.
Thank you,
Peter

**Comment by ChrisKian** [comment]
Looks good, forwarded to https://github.com/drewbrokke/liferay-portal/pull/693

**Pull request closed without merging**
