### PR TITLE
LPS-109947 - add copyFile method as alternative to updateFile to prevent NTFS issue

### PR DESCRIPTION
**Pull request by wanderlast**
Hi Chris!

This fix adds API similar to updateFile(long, long, long, String) that copies (adds) rather than updates (adds and deletes) to Master. The use of copy as an alternative to update is inspired by this fix: f9a37005530f0d8cb881191ee589e2a9ac689e27. This is to prevent an NTFS issue which arises when an attempt to delete a file is processed before all operations are complete on it. Due to the readdition of API/method calls in LPS-110213, this fix now applies to Master as well.

Please let me know if you have any questions about this. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Looks good, sent to https://github.com/shuyangzhou/liferay-portal/pull/8932

**Pull request closed without merging**
