### PR TITLE
LPS-92284 Don't show View in Context link for blog entries with no suitable context

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LPS-92284 Don't show View in Context link for blog entries with no suitable context (i.e., don't display View in Context links that would result in a 404)

### CODE REVIEW

**Comment by jrao** [comment]
ci:test:sf

**Comment by jrao** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hey @jrao,
Looks like you have a real SF error:

> [java] java.lang.Exception: Found 1 formatting issues:
> [java] 1: Do not use com.liferay.registry classes in modules, see LPS-62989: ./modules/apps/blogs/blogs-web/src/main/java/com/liferay/blogs/web/internal/util/BlogsUtil.java (SourceCheck:JavaModuleIllegalImportsCheck)

If it won't take you more than an hour or two to resolve, I'll leave the branch open, otherwise please close it and resend when ready.

**Comment by jrao** [comment]
Closing for now. Will fix and resend.

**Comment by jrao** [comment]
Sent https://github.com/ChrisKian/liferay-portal/pull/118

**Pull request closed without merging**
