### PR TITLE
LPS-93992 Prevent noninstanceable portlets from being added to page when the portlet has already been embedded on the page

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LPS-93992 Make sure that portlet preferences are added to the database for embedded portlets so that they'll be detected the same way as manually added portlets

### CODE REVIEW

**Comment by jrao** [comment]
ci:test:sf

**Comment by jrao** [comment]
ci:test:relevant

**Comment by jrao** [comment]
ci:test:stop

**Comment by jrao** [comment]
ci:test:sf

**Comment by jrao** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hey @jrao,

Can you confirm your solution still resolves the issue found in LPS-88060?  Since there are no tests directly related to this, I want to double check and make sure everything is good before forwarding.  Thanks!

**Comment by jrao** [comment]
@ChrisKian Looks like LPS-88060 is still an issue. Working on making sure fix resolves both issues.

**Comment by jrao** [comment]
rebased on master and resent here: https://github.com/ChrisKian/liferay-portal/pull/130

Since LPS-88060 is still an issue regardless of whether the fix for this issue is merged or not, I think we should go with this fix.

**Pull request closed without merging**
