### PR TITLE
LPS-95606

### PR DESCRIPTION
**Pull request by Alec-Shay**
Relevant tickets:

https://issues.liferay.com/browse/LPP-33858
https://issues.liferay.com/browse/LPS-95606

Previously, [LPS-90724](https://issues.liferay.com/browse/LPS-90724) fixed an issue in which, if repeatable fields do not have values filled in for all (relevant) translations, then the values will be mixed up and updated incorrectly (this is because when they are processed in the Java later on, it has less values than it needs, and it can no longer distinguish the correct order, or match them to the proper fields if out of order). It fixed that by forcing any missing translations to be populated by copying the default translation once the content is published.

That fix did not properly address nested fields though, as nested fields are added with the repeated field all at once with a template, so the `originalFields` variable can't register them the same way. This fix refactors the code added in LPS-90724 so that it can recursively traverse through each of the nested fields and populate them as well.

Note that in master, LPS-90724 caused an issue specifically for IE11, [LPS-93851](https://issues.liferay.com/browse/LPS-93851), but the fix for that also ended up removing the functionality from the fix for LPS-90724 because the function would return early from that change. To address that, I also separately added this commit (https://github.com/ChrisKian/liferay-portal/commit/0c12c31af243d96e61613fccdd548864e0396f66), though it would have been fixed by the refactor anyway.

Please let me know if there are any questions or concerns with this. Thank you.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by Alec-Shay** [comment]
Hmm... some of the test failures related to forms seem a bit sketchy... but I'm not sure how 'unique' they are exactly. I did get some of them inadvertently while I was testing this other unrelated fix with CI as well: 
 https://github.com/Alec-Shay/liferay-portal/pull/38#issuecomment-493228187

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
Looks good, sent to https://github.com/jeyvison/liferay-portal/pull/367

**Pull request closed without merging**
