### PR TITLE
LPS-99587 - Add tests to check if prerequisites have been met before calling setDigest

### PR DESCRIPTION
**Pull request by wanderlast**
https://issues.liferay.com/browse/LPP-34757
https://issues.liferay.com/browse/LPS-99587

Notes from @jesseyeh-liferay:

> ## Problem
> 
> This is a continuation of this [pull request](https://github.com/brianchandotcom/liferay-portal/pull/79098) for [LPS-99587](https://issues.liferay.com/browse/LPS-99587) that adds the required tests.
> 
> ## Solution
> 
> Tests have been added to verify that the prerequisites, `setEmailAddress` and `setScreenName`, have been called prior to calling `setDigest`. The tests check against all calling order permutations (i.e., the order in which `setEmailAddress` and `setScreenName` are called relative to `setDigest`) for `IllegalStateException` when the test should fail.

### CODE REVIEW

**Comment by wanderlast** [comment]
SF test passed here: https://github.com/wanderlast/liferay-portal/pull/29#issuecomment-544655450
Failures didn't look relevant on relevant test, but re-running just in case.

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:stop

**Comment by ChrisKian** [comment]
Looks good, sent to https://github.com/stian-sigvartsen/liferay-portal/pull/200

**Pull request closed without merging**
