### PR TITLE
LPS-75045

### PR DESCRIPTION
**Pull request by wanderlast**
Hi Chris!

LPS: https://issues.liferay.com/browse/LPS-75045

The issue displayed in this LPS is that users were not reindexed upon an Organization's parent organization changing. This meant that, upon a change, users did not have access to content they should have access to until a reindex was triggered. The solution in this LPS is a model listener that, upon a change to an organization, triggers a reindex of all relevant users.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:retest

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hey @wanderlast,

The semantic versioning errors look related.  Mind taking a look and re-pushing your changes?

**Comment by wanderlast** [comment]
Yep, I'll fix those and repush when CI comes back up.

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Forwarded to Jonathan.  See https://github.com/jonathanmccann/liferay-portal/pull/1652

**Pull request closed without merging**
