### PR TITLE
LPS-71001

### PR DESCRIPTION
**Pull request by amadeafejes**
https://issues.liferay.com/browse/LPS-71001

Hi Crhis,

It's related to the SME Request I've created for you.

Thanks!

### CODE REVIEW

**Comment by amadeafejes** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:stop

**Comment by amadeafejes** [comment]
ci:reopen

**Comment by amadeafejes** [comment]
ci:retest

**Comment by amadeafejes** [comment]
ci:retest

**Comment by ChrisKian** [comment]
See https://github.com/amadeafejes/liferay-portal/pull/1

**Pull request closed without merging**
