### PR TITLE
LPS-132576 Use context's total

### PR DESCRIPTION
**Pull request by markgulacsy**
Hi @ChrisKian,

Could you please review this pull request?
I could not find where this `total` variable is initialized, so I have changed it to context total which is initialized properly.

Thank you and best regards,
Mark

### CODE REVIEW

**Comment by markgulacsy** [comment]
ci:test:relevant
ci:test:sf

**Comment by markgulacsy** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
Hi @ChrisKian ,
I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.
Thank you and best regards,
Marci

**Comment by ChrisKian** [comment]
Hi @markgulacsy and @MarcellGyopos,
Sorry for the late reply; this one slipped under my radar.  The problem is this doesn't fall under USM category, so I won't be able to forward it.  I believe it should go to liferay-lima.

That being said, since I made you wait for a reply, I've looked through the code and can offer a bit of guidance:
The `total` variable is derived from the searchContainer creation.  Basically, when we construct the searchContainer, we're able to set a `total` value for it, see [this example](https://github.com/liferay/liferay-portal/blob/master/modules/apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/common/websites.jsp#L71).  Whatever we have set is created into a local variable for use.

The issue with doing this in this particular file is how `total` is derived.  We need the `assetEntryQuery` to be populated, which requires the `searchContainer` for it's basic params.  So I believe we have two ways to resolve this issue:
1. very similar to your fix, set `total = searchContainer.getTotal();`
2. For a more complete fix, we would need to set the correct `total` value in the search container, and also possibly set the searchContainerResults using the taglib as well ([here's en example of that](https://github.com/liferay/liferay-portal/blob/master/modules/apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/common/websites.jsp#L73-L75))

It's probably acceptable to go with the first option, since the second requires a bit of a rework of the entire file.  Please let me know if you have any questions, thanks!

**Comment by MarcellGyopos** [comment]
Hi @ChrisKian,
I just wanted to test your suggestion , but before deploy any changes I retested with a fresh master the issue, but it looks like something fixed it before me. I see what you said, but now I'm looking for the LPS what fixed the bug. Could you explain where is total initialised? In the example you sent, total was initialized, but not here.
Thank you.

**Comment by MarcellGyopos** [comment]
Hi @ChrisKian ,
Please ignore my previous comment, I tested with an old db.

**Pull request closed without merging**
