### PR TITLE
[TECNICAL SUPPORT] LPS-89201 Displaying wrong timezone if user is temporarily locked

### PR DESCRIPTION
**Pull request by amadeafejes**
Hi Chris,

I'm resending the fix for LPS-89201. This time I added nearly the same logic into the login.jsp as in the previous pull. My question is this fix appropriate to build a hotfix for the customer? Could you please review this pull?

Let me know if you have any question!

Thanks,
Amadea

https://issues.liferay.com/browse/LPS-89201

### CODE REVIEW

**Comment by amadeafejes** [comment]
ci:test:sf

**Comment by amadeafejes** [comment]
ci:test:relevant

**Comment by amadeafejes** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hi @amadeafejes,

I have forwarded this PR here: https://github.com/topolik/liferay-portal/pull/704
Please see my changes: https://github.com/topolik/liferay-portal/pull/704/commits/5b48c93bc8d03d41c9c968398fec7874872f2f05

I believe these code changes are suitable and safe to deliver early to the client.  Also, I reviewed the PR anyway, but I believe the login portlet actually belongs to the security team, not USM.  Either way I've reviewed it for you.

Thanks!

**Pull request closed without merging**
