### PR TITLE
LPS-92069 Check the classPK returned by asset renderer since it can either be a resource primary key or an entry ID; see LPS-68599

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LPS-92069 Check the classPK returned by asset renderer since it can either be a resource primary key or an entry ID; see LPS-68599

### CODE REVIEW

**Comment by jrao** [comment]
ci:test:sf

**Comment by jrao** [comment]
ci:test:relevant

**Comment by jrao** [comment]
ci:test:integration

**Comment by ChrisKian** [comment]
Made some changes and resent back to you: https://github.com/jrao/liferay-portal/pull/44

If everything looks good with no needs for changes, just let me know and I'll forward it.  Thanks!

**Comment by jrao** [comment]
@ChrisKian Just reviewed your pr ([jrao#44](https://github.com/jrao/liferay-portal/pull/44)) and it looks good. Tested it, it works fine, ready to forward.

**Comment by ChrisKian** [comment]
Sent to https://github.com/inacionery/liferay-portal/pull/174

**Pull request closed without merging**
