### PR TITLE
LPS-105307

### PR DESCRIPTION
**Pull request by wanderlast**
Hi Chris!

https://issues.liferay.com/browse/LPP-35755
https://issues.liferay.com/browse/LPS-105307
https://issues.liferay.com/browse/PTR-1427

This issue relates to behavior that occurs when a parent-child site relationship is broken and an AP exists on the parent site that has the child site as its scope. This leads to issues in AssetPublisherHelperImpl, specifically in getGroupIdFromScopeId since the site that is no longer officially a child site is still identified as one in the portlet preferences. In PTR-1427, Daniel Cuoso stated the following:

> Regarding the code that you refer to, I would like to note that LPS-39630 introduced these exceptions for child and parent sites. With LPS-89942, the export/import of AssetPublisher preferences was changed to throw exceptions aborting the process instead of just warning about them letting it go on.
> 
> Knowing this and taking a look at the code, the PrincipalException should not be thrown (or if thrown, properly caught) when an export or a publish is in progress, warning about the fact that the groupId could not be calculated based on the given scopeId.

Therefore the fix does the following:
We no longer throw an exception for this specific issue and instead run a warn message. Exports therefore are no longer stopped for this issue despite the issue. When importing, issues are fixed since the scope actually corrects itself and therefore no warns occur. 

The warn is fairly noisy. It happens twice and happens not only when exporting but also when interacting with the page that the AP is on. I don't believe this is a bad thing necessarily since I can't see any purposeful case of a client intentionally keeping their AP with an incorrect scope, but it is something that may need to be reconsidered.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Looks good, sent to https://github.com/jkappler/liferay-portal/pull/653

**Pull request closed without merging**
