### PR TITLE
LPS-113325 After performing a search on the Select Role modal the Choose buttons state not updates

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-113325](https://issues.liferay.com/browse/LPS-113325).<br><br>Hey @ChrisKian, I made a number of changes to try to simplify in some spots. Will yyou please look over them and confirm that everything still works as intended? If so you can go ahead and forward to Brian. cc @rolandpakai<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
Hi @drewbrokke 
could you please review and push it forward?
Thanks, Roland

**Comment by ChrisKian** [comment]
ci:forward

**Comment by ChrisKian** [comment]
Changes look good and still work properly.  Attempting to forward PR now.

**Comment by rolandpakai** [comment]
Hi @ChrisKian
could you please forward this PR?
Thanks, Roland

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
