### PR TITLE
[TS] LPS-117666 my-user-account service does not return inherited regular roles

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-117666](https://issues.liferay.com/browse/LPS-117666)

Hi Chris,

I hope you can review my changes. You are already familiar with the issue due to [PTR-1819](https://issues.liferay.com/browse/PTR-1819).

To solve this, I used the same approach as Account Settings page to collect the user's inherited regular roles. Basically, I mirrored the __getAllGroups(User)_ method and its dependencies from _UserDisplayContext_. The group filtering rules (originally determined as _InitDisplayContext._filterManageable*_ values) became a bit more simple in the mirrored methods, because in _UserAccountResourceImpl_ we don't have the [portlet contextual data](https://github.com/liferay/liferay-portal/blob/master/modules/apps/users-admin/users-admin-web/src/main/java/com/liferay/users/admin/web/internal/display/context/InitDisplayContext.java#L43-L53) as in the original case.

Please let me know if you have any questions or concerns.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
@ChrisKian , do you think this is good enough for an SDH. Thank you.

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Looks good, sent to https://github.com/drewbrokke/liferay-portal/pull/1131.

And an SDH should be totally fine.

**Pull request closed without merging**
