### PR TITLE
Pr 258

### PR DESCRIPTION
**Pull request by ChrisKian**
@kevhlee I made a couple changes, please take a look and let me know if everything looks alright.  I'll forward once you give me the "ok".

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
Hey @ChrisKian,

I took a look and tested the changes. We still need to have `row.setSkip(true)` or else we get the following result:

result

I've tried doing what you did in commit bf5a45971b3272bb4eb275a8341fab821205efc4, but I think the `<liferay-ui:search-container-row>` tag will always render every row (one way or another) unless we explicitly skip the row using `setSkip(true)`.

**Comment by ChrisKian** [comment]
Hey @kevhlee, how about now?  I added one additional commit here:  https://github.com/ChrisKian/liferay-portal/pull/259/commits/811e85bac5e59ac5be4deab2dd810d8f4a7e6c89

**Comment by ChrisKian** [comment]
ci:test:sf

**Pull request closed without merging**
