### PR TITLE
LPS-79309 Avoid possible NPE

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by ChrisKian** [comment]
Hey @pavel-savinov,

Thanks for your solution, but I don't know if it makes sense to return true in the case where both locales are null.  It could be argued they have the same language (of "null"), but I don't believe that will actually be useful, since we shouldn't continue with null locales.  I think the best solution is to [return false if either locale is null](https://gist.github.com/ChrisKian/1674422d7cc7f2bb727356d608f3b127).

If you follow that solution, it won't break any functionality from LPS-77681 and should resolve LPS-79309 as well.  If your solution is identical to mine, please forward it to the next reviewer.

Let me know what you think, thanks!

**Comment by pavel-savinov** [comment]
@ChrisKian, could you please implement it as you would like it to be, but without introducing an NPE, because now it causes problems because of that?

**Comment by ChrisKian** [comment]
Forwarded to you @pavel-savinov.  See https://github.com/pavel-savinov/liferay-portal/pull/160

**Pull request closed without merging**
