### PR TITLE
LPS-127143

### PR DESCRIPTION
**Pull request by jesseyeh-liferay**
[LPS-127143](https://issues.liferay.com/browse/LPS-127143)

After being redirected to a custom 404 .jsp page, a `NoSuchLayoutException`/`NoSuchGroupException` session error is added. As a result, when navigating back to a previous page, a corresponding error is shown.

Instead of removing the session error after the 404 resolves (see [LPS-123054](https://github.com/liferay-lima/liferay-portal/pull/1133/commits/ab5aa5a4a7757d0909bd7e406d762ed30df612f7)), this solution avoids adding the session error to begin with in the event of a redirect to a custom 404 page.

### CODE REVIEW

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by jesseyeh-liferay** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Looks good, sent to https://github.com/liferay-lima/liferay-portal/pull/1450

**Pull request closed without merging**
