### PR TITLE
LPS-97605 Ensure that a verification process failure is recorded when bad ddm structure data is encountered

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LPS-97605 Ensure that a verification process failure is recorded when bad ddm structure data is encountered

### CODE REVIEW

**Comment by jrao** [comment]
ci:test:sf

**Comment by jrao** [comment]
ci:test:relevant

**Comment by jrao** [comment]
ci:stop

**Comment by jrao** [comment]
Fixed SF error

**Comment by jrao** [comment]
ci:test:sf

**Comment by jrao** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hey @jrao,

After a bit of investigation, I know your solution will work, but I'm wondering if it can be improved.

First, let me confirm some behavior with you.  If you have bad data and run the executeAll command, it will output error messages related to the specific data, correct?  Now, if you execute the same command with several instances of bad data, is an error message thrown for each one, or just the first?

This is important because with your change, it will throw an exception on the first instance of bad data, and halt all other verify processes from happening afterwards.  It's good the error will be caught, but it may be nice if all errors are found on the initial run (this is especially true if executeAll finds all the errors the first run through).

I'm going to look into this issue a bit further on Monday, but if you can also take a second look and test my hypothesis, I would greatly appreciate that.

Thanks!

**Comment by jrao** [comment]
With my fix applied, if I have bad data and run the execureAll command, I get these two error messages:

`ERROR - Invalid data for DDM structure 34001 causes exception`

`ERROR - com.liferay.portal.verify.VerifyException: com.liferay.dynamic.data.mapping.validator.DDMFormValidationException$MustSetValidIndexType: Invalid index type set for field Boolean3b45
com.liferay.portal.verify.VerifyException: com.liferay.dynamic.data.mapping.validator.DDMFormValidationException$MustSetValidIndexType: Invalid index type set for field Boolean3b45
...
Caused by: com.liferay.dynamic.data.mapping.validator.DDMFormValidationException$MustSetValidIndexType: Invalid index type set for field Boolean3b45
...`

Your hypothesis is correct - with a second piece of bad data, only the first piece of bad data is reported.

**Comment by ChrisKian** [comment]
Looks good, forwarded here: https://github.com/achaparro/liferay-portal/pull/330

**Pull request closed without merging**
