### PR TITLE
[TS] LPS-131525

### PR DESCRIPTION
**Pull request by balazssk**
Hi @ChrisKian ,

[VerifyGroup](https://github.com/liferay/liferay-portal/blob/8625f5ed6c4ca75a6520153cab32d121d75fa2bb/portal-impl/src/com/liferay/portal/verify/VerifyGroup.java#L233) uses Collection.contains to filter for userGroupGroupRoles that are present in the Staging group but not in the Live group. This however won't work with the default Object#equals, so I'd like to add this implementation.

The solution is based on https://github.com/liferay/liferay-portal/commit/35e3d3329ccba0262adb03fc4b81dc8c75618e27#diff-e89f78642ff2532ec9fbd54692f8cf0a1168886d7c7337694925e3299d9f78b9 .

Can you please review?
https://issues.liferay.com/browse/LPS-131525

Thank ,
Balázs

### CODE REVIEW

**Comment by ChrisKian** [comment]
Hi @balazssk,
I'd like better steps to reproduce; I don't think running a script to force in staging roles is viable.  Could you try a FP level before LPS-61795 to see if you can reproduce without a script?

**Comment by balazssk** [comment]
Hi @ChrisKian ,
Sadly I can't provide better reproduction steps.
The whole investigation rests on the shoulders of 
1. LPS-61795 providing the proof that it somehow was possible to create userGroupGroupRoles for staging sites 
2. the help center ticket's stacktrace indicating that verifyStagingUserGroupGroupRolesAssignments fails
3. and UserGroupGroupRoleLocalServiceUtil#addUserGroupGroupRoles not checking the groupId for Staging

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
Hi @ChrisKian ,
Can you please share your thoughts on my reasoning above?

**Comment by ChrisKian** [comment]
Hi @balazssk and @GezaGroma,
Apologies for not forwarding the PR sooner; I was on PTO.

I've sent the PR here: https://github.com/liferay-usm/liferay-portal/pull/22

**Pull request closed without merging**
