### PR TITLE
LPS-80841

### PR DESCRIPTION
**Pull request by wanderlast**
Hi Chris!
LPP: https://issues.liferay.com/browse/LPP-29923
LPS: https://issues.liferay.com/browse/LPS-80841

The issue is that site names in URLs are being changed to the publishing site. Per LPS-78466 (50bee79c29da67788164b44bb68454f20932f233), we must use the Friendly URL for external groups. The fix checks if the group is the same before using the UUID. Please let me know if you have any questions or concerns.

Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hey @wanderlast,

Looks like your changes (although correct) may have caused some tests to fail (likely the ones I added).  Can you run the tests locally and see if they fail?  If so and you have trouble fixing them, let me know and I'd be happy to help.

https://github.com/liferay/liferay-portal/commit/867f0d94416dbfb2ca359e00315b2317b20d8548

thanks!

**Comment by wanderlast** [comment]
Hi @ChrisKian,

Got it, I'll take a look at them. Thanks!

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Looks good to me.  Forwarded to Mate: https://github.com/matethurzo/liferay-portal/pull/2045

**Pull request closed without merging**
