### PR TITLE
LPS-88984 Add Youtube portlet iframe resizing when portlet is added to page, dragged to new column, or window is resized

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LPS-88984 Add Youtube portlet iframe resizing when portlet is added to page, dragged to new column, or window is resized

### CODE REVIEW

**Comment by jrao** [comment]
ci:test:sf

**Comment by jrao** [comment]
ci:test:relevant

**Comment by jrao** [comment]
See https://github.com/gregory-bretall/liferay-portal/pull/157#issuecomment-464177661

**Comment by ChrisKian** [comment]
Hey Jesse,
I'll try to get to this issue Tuesday

**Comment by ChrisKian** [comment]
Looks good, sent to https://github.com/jonmak08/liferay-portal/pull/2045

**Pull request closed without merging**
