### PR TITLE
LPS-90474 Change log level from warn to trace so warning doesn't appear in log by default when importing documents

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LPS-90474 Change log level from warn to trace so warning doesn't appear in log by default when importing documents

### CODE REVIEW

**Comment by jrao** [comment]
ci:test:sf

**Comment by jrao** [comment]
ci:test:relevant

**Comment by jrao** [comment]
@ChrisKian Changing the log level from warn to trace is the simplest fix I could think of. Another option might be to entirely remove the logging that the string could not be decrypted but I'm not sure why it was added in the first place.

**Comment by jrao** [comment]
Looking at this again, I think DEBUG is a better log level for this message than TRACE. If we even want to keep the message at all.

**Comment by jrao** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
Hey @jrao,

I don't believe this is the correct solution.  In this scenario, we are quieting a WARN message which shouldn't occur in the first place, or basically just sweeping the whole problem under the rug.

What is interesting is why we are failing, and the fact we are returning afterwards.  Basically, we are trying to decrypt an unecrypted string, thus throwing an error and returning 0.  However, we have the userId we want to impersonate, it's just not encrypted.  If anything, that should give us more power to use it, since it's clear.  I don't see a reason why we must decrypt the userId in order to use it, given an already unencrypted userId is provided.

I think the correct solution will be to check with the "doAsUserIdString" is either encrypted (in which case we decrypt it) or a valid long (in which case we skip the decryption step).  If it is neither, the WARN message should be outputted and we return 0 as we normally would.

Let me know if you have any questions.  Thanks!

**Comment by jrao** [comment]
@ChrisKian Makes sense. Implemented the fix you suggested here: https://github.com/ChrisKian/liferay-portal/pull/106

**Pull request closed without merging**
