### PR TITLE
[TS] LPS-143970 Deleting an lpkg file does not remove the app from App

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Dear @ChrisKian,

I have created a fix based on what was discussed on the previous pull.
Please review this fix, and if you approve this change, please forward it to the next approver,

Thank you,
Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
Hey @peterpetrekanics,

This think this is a good **_first-half_** of the solution.  These changes will prevent any already uninstalled apps from being displayed, which is important.  The current solution can be given as an SDH workaround for your client.

However, I'd like to also see a portion of the solution which **_prevents_** any newly deleted/uninstalled apps from ever reaching this state, like how we do with jars.  See [my comparisons here](https://issues.liferay.com/browse/PTR-2753?focusedCommentId=2574521&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2574521) and look for the "(bug)" items.

Please let me know if you have any questions, thanks!

**Comment by peterpetrekanics** [comment]
Hi @ChrisKian ,
Thank you very much for your help!
One quick question though:
I would like to release an SDH as discussed, but my change is not included when I generate a hotfix within the Patcher Portal.
It may be that since my change is affecting com.liferay.marketplace.app.manager.web.jar, this wiki should be followed:
https://liferay.atlassian.net/wiki/spaces/SUPPORT/pages/1854341491/Support+Marketplace+App+Release+SOP
However I can not find the MP manager app there either.
My question is: how should I patch the com.liferay.marketplace.app.manager.web.jar file?
Many thanks,
Peter

**Comment by ChrisKian** [comment]
Hi @peterpetrekanics,
The marketplace entry is missing for 7.3 in patcher (you can see 7.2 has the "DXP 7.2 Liferay Marketplace" option available).  You'll need to reach out to the patcher team in order for them to add the tag to the available builds.  Once completed, you'll be able to submit the same fix with the "DXP 7.3 Liferay Marketplace" option, and the hotfix should work.

**Pull request closed without merging**
