### PR TITLE
[TS] LPS-107670 Do not store empty dictionary in DB

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-107670](https://issues.liferay.com/browse/LPS-107670)

Hi @ChrisKian,

I hope you can review my changes.

The issue is known for your from [PTR-1475](https://issues.liferay.com/browse/PTR-1475). The solution is simple and generic as we discussed. Manual and automated test results are promising.

Please let me know if you have and questions and concerns.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
@ChrisKian , please also let me know if you think it is safe to give the solution out as an SDH. Thank you!

**Comment by ChrisKian** [comment]
Hi @istvansajtos,

Your PR looks good, so I've forwarded it to https://github.com/drewbrokke/liferay-portal/pull/963.

It should be safe for an SDH, but you may want Drew to review it first just in case there is some minor edge-case we haven't considered (he's usually pretty quick to review).

Also, you'll want to write a script for the client to remove the existing null configuration.  Although manual deletion works, we try not to advise that, and a script looks more polished.

Let me know if you have any questions, thanks!

**Comment by istvansajtos** [comment]
Thank you, @ChrisKian !

**Pull request closed without merging**
