### PR TITLE
LPS-79549: Exception messages now inform the exact amount of characters required for each constraint.

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hey @linolaoj,

The PR looks good, but I'd like to see the same logic placed in [update_password.jsp](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/portal/update_password.jsp) as well.  Please resend once you mave made those changes.  Thanks!

**Comment by renatodepaiva** [comment]
Thanks @ChrisKian! I will update the branch and will resend it again after the tests.

**Comment by renatodepaiva** [comment]
Here it is: https://github.com/ChrisKian/liferay-portal/pull/60

**Pull request closed without merging**
