### PR TITLE
LPS-60047 SF - simplify

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey @ChrisKian 
I think this code would do the same thing. Can you please verify? thanks!

cc @jonathanmccann

### CODE REVIEW

**Comment by ChrisKian** [comment]
HeyJulio,

When I was creating the fix I tried using the portletPermissionUtil.contains() method as well.  however, I found it results in the following infinite loop:

* PortletPermissionUtil.contains(PortletPermissionUtil.java:149)
* PortletPermissionImpl.contains(PortletPermissionImpl.java:216)
* PortletPermissionImpl.contains(PortletPermissionImpl.java:226)
* PortletPermissionImpl.contains(PortletPermissionImpl.java:273)
* PortletPermissionImpl.contains(PortletPermissionImpl.java:342)
* PortletPermissionImpl.hasCustomizePermission(PortletPermissionImpl.java:633)
* LayoutTypePortletImpl.isPortletCustomizable(LayoutTypePortletImpl.java:790)
* LayoutTypePortletImpl.getColumn(LayoutTypePortletImpl.java:1399)
* LayoutTypePortletImpl.getColumnValue(LayoutTypePortletImpl.java:1443)
* LayoutTypePortletImpl.getUserPreference(LayoutTypePortletImpl.java:1697)
* PortletPermissionUtil.contains(PortletPermissionUtil.java:149)

Please let me know how we should proceed.

Thanks!

**Comment by juliocamarero** [comment]
Hey @ChrisKian 

I think the last commit I added should avoid that. Could you please verify?

thanks!

**Comment by ChrisKian** [comment]
Hey @juliocamarero,

I just tested your changes and everything looks good!

**Comment by juliocamarero** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/32263

**Pull request closed without merging**
