### PR TITLE
Lps 78055

### PR DESCRIPTION
**Pull request by joshuacords**
Ticket: [LPS-78055](https://issues.liferay.com/browse/LPS-78055)

I removed the choice Jared added based on what I found described [here](https://github.com/joshuacords/liferay-portal/pull/16#issuecomment-377055314).

Notes from @jareddomio
Problem: After a user Confirms/ignores a request notification the notification does not disappear from the search container. Instead the notification's body is replaced with the message "Notification no longer applies, notification for invite members was deleted".

Solution: The cause of the problem was the search containers results were being populated with all of the notifications that were designated as 'actionRequired'. This filter was too broad because this includes request notifications that the user already clicked on/archived. The solution was to make sure the search container results were populated with notifications that have 'actionRequired==true' and 'archived==false'. Archived set to false means the notification has not yet been read.

It is also necessary to force a page refresh to get the updated search container to display correctly. In a previous PR I refreshed the page using location.reload() in notification/view.jsp. This was a bad approach because the action was being processed after the page reloaded instead of before. To ensure the page is refreshed after the action is processed I instead submitted the form and set the method to 'post'.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test

**Comment by joshuacords** [comment]
ci:stop

**Comment by joshuacords** [comment]
I modified getAllNotifications to be consistent with the jsp here: https://github.com/ChrisKian/liferay-portal/pull/36/commits/49354545ced2bac69316cd11dbb8f6d676b03531#diff-5cb17d78df6009907efb8a6070f83c8bR57

**Comment by joshuacords** [comment]
These failures aren't related.

**Comment by ChrisKian** [comment]
I agree.  I doubt these changes would cause any test errors.  Forwarded to Jonathan: https://github.com/jonathanmccann/liferay-portal/pull/1588

**Pull request closed without merging**
