### PR TITLE
LPS-88275 Multiple LDAP System Settings entries

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-88275](https://issues.liferay.com/browse/LPS-88275).

Hey Chris, will you please look over my changes and let me know if it looks ok?

Your fix works fine, but in my opinion the true issue is with how we're indexing factory configurations. Since the indexer is only interested in the structure of each configuration interface rather than individual configuration instances, there should only ever be one document per configuration interface. When the Config Admin Web module first loads it indexes all ConfigurationModels irrespective of whether or not they have an actual configuration backing them.  At that time, even factory configuration are indexed with just the base factory pid, and that's all it should ever be.

Let me know if this makes sense to you, or if I'm missing something.  Thanks!

@pei-jung @stsquared99 @alee8888

### CODE REVIEW

**Comment by drewbrokke** [comment]
@JorgeFerrer @mhan can you please confirm that fe746e4cdb26751295c856ed3e6430792b584d18 is correct?

**Comment by ChrisKian** [comment]
Hey @drewbrokke,

After testing you changes, I can confirm everything works as expected.  Thanks for looking into this issue!

**Comment by JorgeFerrer** [comment]
> @JorgeFerrer @mhan can you please confirm that [fe746e4](https://github.com/ChrisKian/liferay-portal/commit/fe746e4cdb26751295c856ed3e6430792b584d18) is correct?

I think it's correct. Since we don't want to index each factory instance, but the configuration model itself. It's also consistent with the doDelete() model.

What I'd like you to doublecheck is that when factory=false, getFactoryPid returns the same as getID.

**Comment by drewbrokke** [comment]
> What I'd like you to doublecheck is that when factory=false, getFactoryPid returns the same as getID.

@JorgeFerrer I appreciate the double-check.  It should be consistent.  

`getFactoryPid` returns the ID defined in the Meta.OCD tag: [ConfigurationModel.java#L146]( https://github.com/liferay/liferay-portal/blob/master/modules/apps/configuration-admin/configuration-admin-web/src/main/java/com/liferay/configuration/admin/web/internal/model/ConfigurationModel.java#L146).  

This is the same as what is returned by `getID` when there is no configuration instance backing the model: [ConfigurationModel.java#L165](https://github.com/liferay/liferay-portal/blob/master/modules/apps/configuration-admin/configuration-admin-web/src/main/java/com/liferay/configuration/admin/web/internal/model/ConfigurationModel.java#L165).

So it should always equal the PID declared in the interface.

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/67454.

**Comment by drewbrokke** [comment]
Thanks for your input, all!

**Pull request closed without merging**
