### PR TITLE
LPS-94581 Restrict size of portal preferences query; remove customizable page user preferences when page is updated from customizable to not customizable

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LPS-94581 Restrict size of portal preferences query; remove customizable page user preferences when page is updated from customizable to not customizable

### CODE REVIEW

**Comment by jrao** [comment]
@ChrisKian Addressed your feedback from https://github.com/ChrisKian/liferay-portal/pull/134

1. Regarding your first point, I investigated and found that user preferences were not deleted when a page was modified from being customizable to being not customizable. I added the call to delete the user page customizations in this situtation.

2. Since user page customizations are all at the individual scope, I updated the call to use a dynamic query to only retrieve portal preferences at the individual scope. Given the schema of the PortalPreferences table, it's hard to see how to optimize further.

3. As we discussed, I think creating a new PortalPreferencesImpl is actually the best approach given that there are two different PortalPreferences classes, one of which wraps the other.

One further point to think about: Should we add a message specifying that user page customizations are deleted when a page is modified from being customizable to not customizable? Admins might be used to the old behavior and think they can play with the customizable setting without any danger of losing data.

**Comment by jrao** [comment]
ci:test:sf

**Comment by jrao** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Forwarded to https://github.com/ealonso/liferay-portal/pull/2362
I made a couple changes to your PR, but I think you already knew about one.  The customizations are no longer deleted when toggling customizable pages (thanks for catching that one).  the other is how we use the dynamic query; we now query by the namspacePlid as well, so the result set is exactly what we want.

Also, for your commits, it's good you're descriptive, but more commits can mean more confusion.  This is especially true if you modify sections you already have modified (essentially undo your earlier changes), or add SF commits to your own changes.  I know this was done because your changes came in iterations (I asked you to make some changes after your initial PR), but with too many commits, the older commits become redundant and noisy.

Just something to think about, all and all, the changes are good.

**Pull request closed without merging**
