### PR TITLE
LPS-66853

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @ChrisKian 

I added logic to catch the incorrect ordering of finder-column in service.xml.
If you run SF, you'll see there is 8 cases.
Do you mind sorting those, updating usage and stuff?

No need to send back to me, this can go straight to Brian.

Thanks!

**Comment by hhuijser** [comment]
ci:stop

**Comment by hhuijser** [comment]
ci:retest

https://loop.liferay.com/home/-/loop/feed/3506548

**Comment by hhuijser** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
Hi @hhuijser,

I'm not really sure how the finders are being ordered now.  I have tried both alphabetical by finder name and the order the columns appear, but neither work.

And how am I able to run the source formatter for modules within portal code?  This is for LPS-69171 right?

Thanks!

**Comment by hhuijser** [comment]
@ChrisKian 

Finder are sorted by:
- number of columns
- order of how columns appear in the table

Finder-columns sorted by:
- order of how columns appear in the table

Running ant format-source from portal-impl, will also run SF for all files in modules

Yes, this one applies what you did in LPS-69171 to all service.xml

**Comment by ChrisKian** [comment]
Hi @hhuijser,

When I run ant format-source from portal-impl, I can see the following finders appear: 
```
[java] Incorrect order 'finder': Layout G_P_T: ./out/production/portal-impl/com/liferay/portal/service.xml ?
[java] Incorrect order 'finder': BlogsEntry C_LtD_S: ./out/production/portal-impl/com/liferay/portlet/blogs/service.xml test
[java] Incorrect order 'finder': BlogsEntry C_S: ./out/production/portal-impl/com/liferay/portlet/blogs/service.xml
[java] Incorrect order 'finder': BlogsEntry C_U_S: ./out/production/portal-impl/com/liferay/portlet/blogs/service.xml
[java] Incorrect order 'finder': BlogsEntry G_LtD_S: ./out/production/portal-impl/com/liferay/portlet/blogs/service.xml
[java] Incorrect order 'finder': BlogsEntry G_S: ./out/production/portal-impl/com/liferay/portlet/blogs/service.xml
[java] Incorrect order 'finder': BlogsEntry G_U_LtD_S: ./out/production/portal-impl/com/liferay/portlet/blogs/service.xml
[java] Incorrect order 'finder': BlogsEntry G_U_S: ./out/production/portal-impl/com/liferay/portlet/blogs/service.xml
[java] Incorrect order 'finder': BookmarksFolder G_P_S: ./out/production/portal-impl/com/liferay/portlet/bookmarks/service.xml
[java] Incorrect order 'finder': DLFileEntry G_U: ./out/production/portal-impl/com/liferay/portlet/documentlibrary/service.xml
[java] Incorrect order 'finder': DLFolder G_P_N: ./out/production/portal-impl/com/liferay/portlet/documentlibrary/service.xml
[java] Incorrect order 'finder': ExpandoValue T_R: ./out/production/portal-impl/com/liferay/portlet/expando/service.xml
[java] Incorrect order 'finder': JournalArticle C_T: ./out/production/portal-impl/com/liferay/portlet/journal/service.xml
[java] Incorrect order 'finder': JournalFolder G_P_N: ./out/production/portal-impl/com/liferay/portlet/journal/service.xml
[java] Incorrect order 'finder': MBMessage UserId: ./out/production/portal-impl/com/liferay/portlet/messageboards/service.xml 
```

However, none of the finders or columns appear out of order.  It seems more than half of these errors are a situation like this: 
```
<finder name="C_LtD_S" return-type="Collection">
	<finder-column name="companyId" />
	<finder-column comparator="&lt;" name="displayDate" />
	<finder-column name="status" />
</finder>
<finder name="C_LtD_NotS" return-type="Collection">
	<finder-column name="companyId" />
	<finder-column comparator="&lt;" name="displayDate" />
	<finder-column comparator="!=" name="status" />
</finder>
```
It seems the comparator is throwing things off?  However when I switch them, I still receive a formatting error.

Please let me know if I am missing something.  Thanks!

**Comment by hhuijser** [comment]
Hey @ChrisKian 

Something seems to be off with your branch.
For example, "com/liferay/portlet/blogs/service.xml" doesn't exist anymore in master (was moved to modules). For other service.xml files, ordering looks good on my end.

Seems your branch is heavily out of date or you're running on an incorrect branch?

These are the warnings you should be getting: https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/65875/testReport/com.liferay.source.formatter/SourceFormatterTest/testSourceFormatter/

**Comment by ChrisKian** [comment]
Hi @hhuijser,

Thank you for sharing the errors with me; I'm still not sure why I couldn't see them.

I've made the changes, however for the UserLocalService changes, I'm not sure if this is possible without causing a major version change.  Basically, if I correct the service.xml file, I would also want to correct the UserLocalServiceImpl method to accept the arguments in the correct order, which would require me to build service, thus changing portal-kernel API.

I've never done a major version change so I'm not sure what it entails.  If we shouldn't trigger this change, we could either ignore the SF errors for the user, or maybe not change the UserLocalServiceImpl method arguments (the finder would work correctly, we would just use the arguments in reverse order).

Let me know what you think!

**Comment by hhuijser** [comment]
Thanks @ChrisKian 
Can you send what you have to me?
I'll look at it. Feels like simply excluding that single instance is the best way to go.

**Comment by ChrisKian** [comment]
I've sent a pull.  See https://github.com/hhuijser/liferay-portal/pull/2765

**Pull request closed without merging**
