### PR TITLE
LPS-110498 - revert changes made in LPS-67183 to allow for newlines to be used in Message Board posts

### PR DESCRIPTION
**Pull request by wanderlast**
Hi Chris!

https://issues.liferay.com/browse/LPP-36743
https://issues.liferay.com/browse/LPS-110498

Currently adding newlines to a message board post using the enter key will not work since they are stripped upon posting, leading to a post that should read:

A
B
C

to read as

ABC

This was caused by the solution added in [LPS-67183|https://issues.liferay.com/browse/LPS-67183]. Per the product team's agreement in [PTR-1599|https://issues.liferay.com/browse/PTR-1599], we're reverting LPS-67183 since the feature added is nice to have, but not as impactful as being able to use newlines in a post. I'll be creating a related LPS to readd that feature at a later date, but for now this is more harmful and therefore more important.

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Looks good, forwarded to https://github.com/ambrinchaudhary/liferay-portal/pull/322

Also @wanderlast, we are trying to reserve "relevant" testing for engineering to conserve CI resources.  Please refrain from using such tests on PRs which remain in support.  Thanks!

**Comment by wanderlast** [comment]
Yep, I autopiloted and totally forgot. Thanks for the reminder!

**Pull request closed without merging**
