### PR TITLE
LPS-92784

### PR DESCRIPTION
**Pull request by Preston-Crary**
Can you double check my changes, thanks!

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevan

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
I can confirm the failing tests are related.  Ill look into this further tomorrow.

**Comment by ChrisKian** [comment]
Resent here with test failures resolved: https://github.com/Preston-Crary/liferay-portal/pull/729

**Pull request closed without merging**
