### PR TITLE
Jared domio lps 78055

### PR DESCRIPTION
**Pull request by joshuacords**
Ticket: [LPS-78055](https://issues.liferay.com/browse/LPS-78055)

You can see that the proper database call is here: https://github.com/joshuacords/liferay-portal/blob/91c2cb73c129cd1544d653ec7df2de21406d0b9c/modules/apps/collaboration/notifications/notifications-web/src/main/java/com/liferay/notifications/web/internal/util/NotificationsUtil.java#L72-L75
Jared's code change in the jsp matches it.

I'm not 100% that the location.reload(true); is the best approach to reload but I don't know of a better one. 

Notes from @JaredDomio:
Problem: After a user Confirms/ignores a request notification the notification does not disappear from the search container. Instead the notification's body is replaced with the message "Notification no longer applies, notification for invite members was deleted".

Solution: The cause of the problem was the search containers results were being populated with all of the notifications that were designated as 'actionRequired'. This filter was too broad because this includes request notifications that the user already clicked on/archived. The solution was to make sure the search container results were populated with notifications that have 'actionRequired==true' and 'archived==false'. Archived set to false means the notification has not yet been read.

It was also necessary to force a page refresh to ensure the search container updates after the user clicks on the request notification.

### CODE REVIEW

**Comment by joshuacords** [comment]
Passing tests here: https://github.com/joshuacords/liferay-portal/pull/15
(Failures unrelated)

**Comment by ChrisKian** [comment]
Looks like the tests didn't complete due to unrelated tck failure.  I'll re-run them here just to be safe.

**Comment by ChrisKian** [comment]
ci:test

**Comment by joshuacords** [comment]
This comment sheds some insight about what should happen to a Request that
has been accepted or ignored:
https://issues.liferay.com/browse/LPS-73875?focusedCommentId=1112402&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1112402

**Comment by ChrisKian** [comment]
CC @joshuacords 

Hey @JaredDomio,

I tested your fix but I don't think it's complete.  I believe you are handling things properly on the front-end, but there are instances when accepting/ignoring the invitation the "Notification no longer applies" message is still present, and the userNotificationEvent entry is still in the DB.

This seems like a race condition to me, likely there is some process accessing the userNotificationEvent (probably in user_notification_entry.jspf) while we are trying to remove/update the entry at the same time, blocking the workflow we want.

Please let me know if you believe I may have made a mistake somewhere, or if there is something I've missed.  If you can reproduce the same issue as I am, feel free to reach out to Josh or myself for some help.

Let me know what you think, thanks!

**Pull request closed without merging**
