### PR TITLE
LPS-111067, LPS-112103 - display styles reset every time we navigate away from a menu

### PR DESCRIPTION
**Pull request by wanderlast**
Hi Chris!

https://issues.liferay.com/browse/LPS-111067
https://issues.liferay.com/browse/LPS-112103

This issue is a fix for an issue that covers a broad range of portlets, so this may need to be looked at by multiple teams. I've purposely kept the different portlets in separate commits so that we can hopefully easily remove them from the pull if the teams decide they want the current behavior to persist. I've tried to sync the behavior with 7.1.x (where the fix that caused this issue does not exist), but many features/portlets exist in Master that do not exist in 7.1 so many of these are merely just a best guess that the team would prefer the display style to _not_ reset. Specifically, the issue is that display styles are not actually passed by parameter when navigating between admin portlets (e.g. going from Web Content to Blogs and then back). Therefore the display style will always reset to whatever the default value is given when retrieving the parameter. It was caused by [LPS-90549](https://issues.liferay.com/browse/LPS-90549) which changed the method of retrieving display styles for a seemingly unrelated bugfix. It appears we've followed that design pattern afterwards which would explain the large number of instances of this issue. I've verified that my changes do not appear to make the bug reoccur.

One notable decision that was made was that in, certain portlets, there are multiple display contexts  (e.g. should the user menu and organizations menu always show the same display style?). It's fairly unclear whether these different menus should share the same display style or not among each other and there are multiple portlets where this occurs. Why this is an issue is that the display style is typically saved in PortalProperties using a combination of the portlet as the namespace and "display-style" as the key. However, if multiple display contexts share the same portlet and therefore the same namespace, than the key must also be distinct for them to remain separate entities. For most areas, I've erred on the side of caution and created separate keys for these redundant entries, using the naming scheme "display-style" for any base contexts that might exist for the portlet (e.g. SiteMembershipsDisplayContext), while following the naming scheme of "display-style-class-name" for other keys (e.g. "display-style-select-organizations" in SelectOrganizationsDisplayContext). The most notable exception is that, due to a specific ticket, Organizations between the site membership portlet and the users admin portlet are kept the same since that ticket outlined it as intentional.

I specifically did not "fix" this behavior in item selectors since it doesn't strike me as expected behavior, but I am more than happy to make the changes if you feel that it would be better that way.

LPS-112103 is a related issue fix where the toolbar in Journal also did not properly retrieve the changed display upon navigation, showing a separate default value. I didn't notice this behavior in other places while testing, but it's possible I may have missed an instance.

Since this is a fairly large fix, please let me know if I can clarify anything or look into anything further for you. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
Looks good, forwarded to https://github.com/ealonso/liferay-portal/pull/2900

**Pull request closed without merging**
