### PR TITLE
LPS-204033 Remove unused @Reference variables - Application Security components

### PR DESCRIPTION
**Pull request by manuelecastro**
[Task Link](https://liferay.atlassian.net/browse/LPS-204033)

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:reevaluate:1297401_9152

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
All removed References variables look correct for removal, and test failures look unrelated.

**Comment by ChrisKian** [comment]
Thanks @manuelecastro, PR combined and forwarded here: https://github.com/liferay-appsec/liferay-portal/pull/1595

**Pull request closed without merging**
