### PR TITLE
LPP-33072 Fix group ID used for permission checking for comments

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LPP-33072 Fix group ID used for permission checking for comments

### CODE REVIEW

**Comment by jrao** [comment]
Hey @ChrisKian , just wanted to get your thoughts on the general idea here of using the group ID of the asset entry instead of the scope group ID. In my testing, the scope group ID used was always the group ID of the guest group (which seems incorrect me).

Note: This pr is for master even though https://issues.liferay.com/browse/LPP-33072 is not reproducible on master. But I think the reason for this is that StagingPermissionChecker.hasPermission is implemented differently in master than in 7.0.x and that the underlying problem (incorrect group ID used) remains in master.

Also, I couldn't find a LPS for this issue. If you agree that this is in fact an issue, I'll create an LPS.

**Comment by jrao** [comment]
ci:test

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
Hey @jrao,
Looking into this issue, I don't think there is a problem in master.  Obviously it isn't reproducible in master, but I think using the scopeGroupId is fine in master too.

The reason this works in master VS 70x is due to LPS-74348, which removes ResourceBlock permissioning (although there is a partial 70x backport, it doesn't completely remove the use of ResourceBlocks).  You can easily see the differences after adding the permission onto the Power User role in the steps to reproduce; in master we update a row in the ResourcePermission table, and in 70x we update the ResourceBlock table.

This isn't to say your solution is wrong for 70x, but it isn't needed in master.  In fact, [the permission check returns true in master at this point](https://github.com/ChrisKian/liferay-portal/pull/105/commits/f96bd4c383098d32cfc7cb37215b4dac04ab7252#diff-86478d1f8ca34f3d44850a691280d3bcR264), so there is no need to change the groupId.  You would only need to change this in master if there was a different bug which was falsely returning true higher up the stack, and in that case, you would also need to fix that issue.

What I would like from your next PR is a bit investigation on why this works in master, why a solution is or isn't needed in master, and why the solution is needed in 70x (ResourceBlocks were removed in 71x, so this issue likely isn't reproducible there).  In cases where master has different functionality from branch, we always want to know why, and ideally keep them as similar as possible (although this probably won't happen if the issue is due to ResourceBlocks, which likely won't ever be removed in 70x).  If it's not possible to keep them the same, that's fine, but we want to cover all our bases before making a unique fix.

Let me know if you have any questions.  Thanks!

**Comment by ChrisKian** [comment]
Also, please create an LPS ticket to track the bug itself.  LPP tickets are for the client's problem (be it bug or not), and LPS tickets are for a bug (not necessarily related to a given client).

**Comment by jrao** [comment]
@ChrisKian Got it. Will continue to investigate!

**Comment by jrao** [comment]
LPS created here: https://issues.liferay.com/browse/LPS-91235

**Comment by jrao** [comment]
> You can easily see the differences after adding the permission onto the Power User role in the steps to reproduce; in master we update a row in the ResourcePermission table, and in 70x we update the ResourceBlock table.

Correction to the above: In 70x, we update the ResourceTypePermission. At least that's what I'm seeing.

**Comment by jrao** [comment]
Investigated further and found that while https://issues.liferay.com/browse/LPS-91235 is not reproducible on master, a related issue is. Created new ticket for this issue: https://issues.liferay.com/browse/LPS-91380

Both LPS-91235 and LPS-91380 are caused by the same underlying problem: The wrong group ID (the scope group ID) is being used in EditDiscussionStrutsAction. Solution is to use the group ID of the asset entry instead.

Sent https://github.com/ChrisKian/liferay-portal/pull/107

**Pull request closed without merging**
