### PR TITLE
LPS-92284 Don't show View in Context link for blog entries with no suitable context

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LPS-92284 Don't show View in Context link for blog entries with no suitable context (i.e., don't display View in Context links that would result in a 404)

### CODE REVIEW

**Comment by jrao** [comment]
ci:test:sf

**Comment by jrao** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
SF test looks relevant: https://github.com/ChrisKian/liferay-portal/pull/118/commits/e588ac2218b79574270b87ac6fa465b69fccafb4#diff-6454c102027e1e35195834d184f38b3dR331

**Comment by jrao** [comment]
@ChrisKian Fixed SF

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
I squashed you SF commit in since we only explicitly declare SF commits when reviewing someone else's code or making large, functionally identical code changes.  Sent to https://github.com/adolfopa/liferay-portal/pull/889

**Pull request closed without merging**
