### PR TITLE
LPS-93431 Rename the upgrade class since UpgradeSchema is used for schema changes between releases, this is specific change due to a bug

### PR DESCRIPTION
**Pull request by achaparro**
Hi @ChrisKian,

Your pull https://github.com/achaparro/liferay-portal/pull/296 looks good, thanks for the analysis.

I have tried to simplify the logic using the method _hasColumnType_ but I have realized that it doesn't work, at least for postgresql, when I debugged it the type from the datbase is different than the defined type when both are varchar. We widely use this method in upgrades so if it doesn't work could be really problematic, would you mind to take a look at it?

For the customer, if you are in a hurry you can deliver your previous pull as SDH since it won't be any problem because the schema version remains the same.

Thanks.
Best regards.

### CODE REVIEW

**Comment by ChrisKian** [comment]
I'll try to take a look at this PR tomorrow, thanks!

**Comment by ChrisKian** [comment]
Hi @achaparro,

I have tested a small script which emulates where you believe you upgrade process is failing, but I have been unable to reproduce your issue.  Each time, VARCHAR (75) columns are properly matched.

Is it possible the upgrade isn't working because  of the change here: https://github.com/ChrisKian/liferay-portal/pull/131/files#diff-b0781b2c26d8a3e0abc1f476fc3e8ac7L3.  This change makes it so any DBs created directly from this code are already resolved.

I can show you my script if needed, but I'll try upgrading using your changes in postgres to see if I can reproduce at all.

**Comment by ChrisKian** [comment]
After testing you solution (excluding [the change here](https://github.com/ChrisKian/liferay-portal/pull/131/files#diff-b0781b2c26d8a3e0abc1f476fc3e8ac7L3), so we would rely only on the upgrade process), I've found the fix to work in postgres 9.6.

Can you please walk me through your testing if you are still unable to get the solution working?  Thanks!

**Comment by achaparro** [comment]
Hi @ChrisKian,

During my tests I altered the column to varchar and executed the upgrade process but the method hasColumnType returned false.

Please share the script and I will do more tests in order to know if I made any mistake.

Thanks!

**Comment by ChrisKian** [comment]
Hey @achaparro,

I think I know the problem.  DBInspector.hasColumnType() checks the column type against the given ModelTable.java class, in this case DDLRecordSetTable.java.  So, according to this class, versionUserId is type BIGINT, regardless of what the table actually is in the DB.

This method doesn't actually check against the DB's column type, thus it isn't useful in our case.  We will need to go with a solution similar to the original one I sent you; it has to query the DB.

I can try refactoring my original code a bit, perhaps adding it to a method for future use as well.  Let me know what you think.

**Comment by ChrisKian** [comment]
Closing, sent to https://github.com/achaparro/liferay-portal/pull/299 with changes.

**Pull request closed without merging**
