### PR TITLE
LPS-87629 Added additional check when getting date range

### PR DESCRIPTION
**Pull request by wanderlast**
https://issues.liferay.com/browse/LPS-87629

Explanation from @nellyliupeng:

> DDMTemplates retrieved through PortletDisplayTemplate portlet are not shown when local staging is turned on from the second iteration and on.
> The date range criteria returns an invalid query statement and prevents proper retrieval of ADTs
> 
> From second iteration and onwards using local staging, the criteria would return ie. `(modifiedDate<=null and modifiedDate>=Tue Nov 20 17:59:42 GMT 2018)`, which returns no results due to the first invalid condition.

> This PR adds an additional check when retrieving date range, which is later added to the query used to retrieve ADTs

Essentially, null isn't a valid end date in a date range, so we check for it.

### CODE REVIEW

**Comment by wanderlast** [comment]
Tests passed: https://github.com/wanderlast/liferay-portal/pull/11#issuecomment-440893478 and https://github.com/wanderlast/liferay-portal/pull/11#issuecomment-440878110

**Comment by ChrisKian** [comment]
Hey @wanderlast and @nellyliupeng,
I have a question about the solution itself and how it works.

I understand having "modifiedDate<=null" will result in the problem, but is there ever a case where we want to check by the start date only?  Is there a way to set the startDate to something in the future and not have an endDate?  If so, wouldn't your fix circumvent the startDate since we wouldn't set any date values in the query? (I looked through the usages of hasDateRange() and it seems to only be used to setting date ranges in various queries).

Let me know what you guys think.  Other than that possible issue, the fix looks fine.

**Comment by nellyliupeng** [comment]
Hello @ChrisKian,

A date range seems to be checked here `PortletDataContextFactoryImpl > validateDateRange(startDate, endDate)`, where it's specifying that `endDate` shouldn't be null even if` startDate` is not. It assumes that date range should have a concrete start and end range (or let both be null) when creating a `PortletDataContext`. Seeing this I'm assuming that a case where endDate is null shouldn't be expected.

Another possible fix is to modify how the query is formed in `PortletDataContextImpl > getDateRangeCriteria()`, and to take into account when `_endDate` is null, so that it returns values from `_startDate` and onwards. But this would require a change in `service.xml`

**Comment by wanderlast** [comment]
Hi @ChrisKian,

This isn't reproducible in Master due to the introduction of changesets fixing the underlying problem, but the code still exists thus the fix being sent to Master. I accidentally omitted that explanation in my copy+paste. Sorry!

**Comment by ChrisKian** [comment]
That works for me, thanks for the explanation.  Forwarded to https://github.com/jonathanmccann/liferay-portal/pull/1724

**Pull request closed without merging**
