### PR TITLE
LPS-91380 Use company ID and group ID from asset entry, not themeDisplay, for permissionChecking

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LPS-91380 Use company ID and group ID from asset entry, not themeDisplay, for permissionChecking

### CODE REVIEW

**Comment by jrao** [comment]
ci:test:sf

**Comment by jrao** [comment]
ci:test:integration

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Looks good, sent to https://github.com/adolfopa/liferay-portal/pull/858

**Pull request closed without merging**
