### PR TITLE
LPS-86455 - add back API for 71x/70x compatibility

### PR DESCRIPTION
**Pull request by wanderlast**
Hi Chris!

This is related to https://issues.liferay.com/browse/LPS-86455 which is a closed ticket. However, the ticket is essentially unbackportable to 71x/70x without significant changes due to various infrastructure differences between Master and 7.1.x. This commit forwardports API that was previously within LPS-86455 but that was later removed in Master due to it being unnecessary or due to an alternative approach being used. This API allows the fix to be viable in 7.1.x.

One example is of the enumeration which was added in 8d1091207a11e4e0ed1f8e1607610353627dd1e6, and then removed in 4b74a48d0407c7af7f68e95b7feebed36edc9a8d to be replaced by a Constants class. Since some of the infrastructure necessary for this fix is located in portal-impl in 7.1.x (specifically the getThumbnailSrc method that is found in DLImpl in 7.1.x, but found in a module in Master), the constants class cannot be properly called and the enum is therefore necessary.

Please let me know if you need any further explanations for this. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hey @wanderlast,

The relevant test seems unrelated, but the SF test does.  Mind taking a look and force-pushing your changes?  Thanks

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
Hi @ChrisKian,
Thanks for looking at this! I fixed the SF error, do you want me to still re-run the relevant tests again?

**Comment by ChrisKian** [comment]
Looks good, sent to https://github.com/adolfopa/liferay-portal/pull/1003

**Pull request closed without merging**
